### PR TITLE
Feat: Add support to handle blocked paths

### PR DESCRIPTION
**Pull request by bemisguided**
The use case that precipitated this is a game where paths are temporarily blocked (i.e. door is closed/locked). This adds a configuration property to the Path Finder called `blocked` which is a Function that takes three parameters: the candidate destination Node, the from Node, and the Link between them. When the Function returns `true`, the path it blocked and is ignored as a valid candidate. 

The tests here are a bit contrived, using a property on the Link to indicate blocked or not, however, in my game the Function will query the game state to see whether the path is actually blocked or not.

### CODE REVIEW

**Comment by anvaka** [comment]
Is this similar to return `Ifninity` value from the `distance` callback of the blocked path?

**Comment by bemisguided** [comment]
> Is this similar to return `Ifninity` value from the `distance` callback of the blocked path?

I see that this would also have the same effect. I could argue that this is a bit more obvious but up to you if you want this PR or not.

**Comment by anvaka** [comment]
I don't mind taking it, and I agree that your approach is more explicit/user friendly. My main concern was around potentially negative effect on performance, but after measuring it with https://github.com/anvaka/ngraph.path.demo/blob/main/measurePerformance.js - I didn't notice any impact, so I merged your solution.

Thank you so much for the contribution!

**Comment by anvaka** [comment]
If you can add a documentation to the README.md file - it would help. No worries if you are not available, I can do it myself and publish tomorrow.

**Comment by bemisguided** [comment]
Sure. I make a PR for that now. I also see I missed adding the blocked to the NBA algorithm. I'll add it there too.

**Pull request merged**
